FROM python:3.11-slim



RUN apt-get update && apt-get install -y --no-install-recommends \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip


WORKDIR /app



#RUN pip install --no-cache-dir torch torchvision \
#    --index-url https://download.pytorch.org/whl/cpu

ENV TORCH_HOME=/app/models
 

RUN pip install torch torchvision \
    --index-url https://download.pytorch.org/whl/cpu

#RUN pip install --no-cache-dir ultralytics

RUN pip install ultralytics


#RUN apt-get update && apt-get install -y --no-install-recommends \
#    build-essential \
#    default-libmysqlclient-dev \
#    pkg-config \
#    && rm -rf /var/lib/apt/lists/*


#RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y --no-install-recommends \
    fonts-dejavu \
    && rm -rf /var/lib/apt/lists/*

COPY ./worker/requirements.txt .
RUN pip install  -r requirements.txt


COPY ./utils/ ./utils/
COPY ./worker/ ./worker/
COPY ./weights/ ./weights/

#RUN python -c "import torchvision.models as models; models.resnet18(weights='DEFAULT')"

CMD ["python", "-m", "worker.script"]
