FROM python:3.11-slim



RUN apt-get update && apt-get install -y --no-install-recommends \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip


WORKDIR /app



RUN apt-get update && apt-get install -y --no-install-recommends \
    fonts-dejavu \
    && rm -rf /var/lib/apt/lists/*

COPY ./worker/requirements.txt .
RUN pip install  -r requirements.txt


COPY ./utils/ ./utils/
COPY ./worker/ ./worker/
COPY ./weights/new-weight.onnx ./weights/new-weight.onnx


CMD ["python", "-m", "worker.script"]
